import { v4 as uuidv4 } from "uuid";

const youtubersData = [
  {
    name: "USB Microphone",
    image: ["/microphone.png", "", ""],
    rating: "4.8",
    price: "87",
  },
  {
    name: "Wireless headset",
    image: ["wireless-headset.png", "", ""],
    rating: "4.2",
    price: "74",
  },
  {
    name: "Huawei Laptop",
    image: ["huawei-laptop.png", "", ""],
    rating: "4.3",
    price: "599",
  },
];

export default youtubersData;


export const developerItemsData = [
  {
    name: "M1 Macbook Pro 2020",
    image: "/macbook-pro.png",
    seller: "Apple",
    rating: "4.9",
    price: "1,999",
  },
  {
    name: "Sanchos Office Desk..",
    image: "/office-desk.png",
    seller: "Sanchos",
    rating: "4.2",
    price: "71.12",
  },
  {
    name: "Puton Coffee Maker, Auto ...",
    image: "/coffee-maker.png",
    seller: "Maddy Workspaces",
    rating: "4.7",
    price: "83",
  },
  {
    name: "Adjustable Office Chair",
    image: "/adjustable-chair.png",
    seller: "JD Electronics",
    rating: "4.5",
    price: "64",
  },
  {
    name: "2.4G Optical Wireless Mouse",
    image: "/wireless-mouse.png",
    seller: "Sears",
    rating: "4.5",
    price: "69",
  },
  {
    name: "Jarvis Hardwood Standing Desk",
    image: "/standing-desk.png",
    seller: "Jarvis Hardwood",
    rating: "4.1",
    price: "1,399",
  },
  {
    name: "Beats Airpods 203 - Wireless",
    image: "/beat-airpods.png",
    seller: "Boats",
    rating: "4.2",
    price: "79",
  },
  {
    name: "Logitech Folio Touch",
    image: "/longitech-folio.png",
    seller: "Jodde Electronics",
    rating: "4.2",
    price: "329",
  },
  {
    name: "Black Slot 5 Shelf Unit",
    image: "/shelf.png",
    seller: "Walmart Electronics",
    rating: "4.3",
    price: "61",
  },
  {
    name: "Portable Bluetooth Speaker",
    image: "/bluetooth-speaker.png",
    seller: "Amazon",
    rating: "4.0",
    price: "36.99",
  },
];


export const allItemsData = [
  {
    id: uuidv4(),
    name: "M1 Macbook Pro 2020",
    image: ["macbook-pro.png"],
    seller: "Apple",
    rating: "4.9",
    price: "1999.47",
    category: "developer",
  },
  {
    id: uuidv4(),
    name: "Sanchos Office Desk",
    image: ["office-desk.png"],
    seller: "Sanchos",
    rating: "4.2",
    price: "71.12",
    category: "developer",
  },
  {
    id: uuidv4(),
    name: "Puton Coffee Maker Auto",
    image: ["coffee-maker.png"],
    seller: "Maddy Workspaces",
    rating: "4.7",
    price: "83.38",
    category: "developer",
  },
  {
    id: uuidv4(),
    name: "Adjustable Office Chair",
    image: ["adjustable-chair.png", "chair2.png", "chair3.png"],
    seller: "JD Electronics",
    rating: "4.5",
    price: "64.57",
    category: "developer",
  },
  {
    id: uuidv4(),
    name: "2.4G Optical Wireless Mouse",
    image: ["wireless-mouse.png"],
    seller: "Sears",
    rating: "4.5",
    price: "69.96",
    category: "developer",
  },
  {
    id: uuidv4(),
    name: "Jarvis Hardwood Standing Desk",
    image: ["standing-desk.png"],
    seller: "Jarvis Hardwood",
    rating: "4.1",
    price: "1399",
    category: "developer",
  },
  {
    id: uuidv4(),
    name: "Beats Airpods 203 - Wireless",
    image: ["beat-airpods.png"],
    seller: "Boats",
    rating: "4.2",
    price: "79",
    category: "developer",
  },
  {
    id: uuidv4(),
    name: "Logitech Folio Touch",
    image: ["longitech-folio.png"],
    seller: "Jodde Electronics",
    rating: "4.2",
    price: "329",
    category: "developer",
  },
  {
    id: uuidv4(),
    name: "Black Slot 5 Shelf Unit",
    image: ["shelf.png"],
    seller: "Walmart Electronics",
    rating: "4.3",
    price: "61",
    category: "developer",
  },
  {
    id: uuidv4(),
    name: "Portable Bluetooth Spea..",
    image: ["bluetooth-speaker.png", "", ""],
    seller: "Amazon",
    rating: "4.0",
    price: "36",
    category: "developer",
  },
  {
    id: uuidv4(),
    name: "USB Microphone",
    image: ["microphone.png", "", ""],
    rating: "4.8",
    price: "87.99",
    category: "developer",
    seller: "Amazon Electronics",
  },
  {
    id: uuidv4(),
    name: "Wireless headset",
    image: ["wireless-headset.png", "", ""],
    rating: "4.2",
    price: "74.78",
    category: "developer",
    seller: "Beats by dre",
  },
  {
    id: uuidv4(),
    name: "Burbun Office Chair",
    image: ["burbun-chair.png", "", ""],
    seller: "Orcc Office App.",
    rating: 4.2,
    price: "301.56",
    category: "developer",
  },
  {
    id: uuidv4(),
    name: "Adjustable Chair",
    image: ["adjustable-chair.png", "chair2.png", "chair3.png"],
    seller: "Orcc Office App.",
    rating: 4.5,
    price: "319.09",
    category: "developer",
  },
  {
    id: uuidv4(),
    name: "Markus Office Chair",
    image: ["markus-chair.png", "", ""],
    seller: "Markus Electronics",
    rating: 4.8,
    price: "432.63",
    category: "creative",
  },
  {
    id: uuidv4(),
    image: ["monitor-stand.png", "", ""],
    name: "Wooden Monitor Stand",
    seller: "Walnus Home",
    rating: 4.3,
    price: "113.92",
    category: "developer",
  },
  {
    id: uuidv4(),
    image: ["headset.png", "", ""],
    name: "Logitech G433 Headset",
    seller: "Zone Electroncs",
    rating: 4.2,
    price: "91.58",
    category: "developer",
  },
  {
    id: uuidv4(),
    image: ["laptop.png", "", ""],
    name: "HP Laptop - 10th generation",
    seller: "Maddy Workspaces",
    rating: 4.6,
    price: "850.00",
    category: "developer",
  },
  {
    id: uuidv4(),
    image: ["watch.png", "", ""],
    name: "Smart Apple Watch SE",
    seller: "Jodde Electronics",
    rating: 4.8,
    price: "319.56",
    category: "developer",
  },
  {
    id: uuidv4(),
    image: ["ipad.png", "", ""],
    name: "Apple iPad Pro Wifi 512GB",
    seller: "Apple",
    rating: 4.8,
    price: "1379.96",
    category: "editor",
  },
  {
    id: uuidv4(),
    image: ["samsung.png", "", ""],
    name: "Samsung Note 22",
    seller: "JD Electronics",
    rating: 4.9,
    price: "1100.89",
    category: "editor",
  },
  {
    id: uuidv4(),
    name: "USB 4port Hub",
    image: ["usb.png", "", ""],
    rating: "4.8",
    price: "33",
    category: "developer",
    seller: "Samsung",
  },
  {
    id: uuidv4(),
    name: "Huawei Laptop",
    image: ["huawei-laptop.png", "", ""],
    rating: "4.3",
    price: "599.00",
    category: "photographer",
    seller: "Huawei ",
  },
  {
    id: uuidv4(),
    image: ["macbook-pro.png", "", ""],
    name: "Apple Macbook Pro 12inch",
    seller: "Apple",
    rating: 4.9,
    price: "1499.99",
    category: "creative",
  },
  {
    id: uuidv4(),
    image: ["camera.png", "", ""],
    name: "JVC Recording Camera 1500L ",
    seller: "Jodde Electronics",
    rating: 4.8,
    price: "319.29",
    category: "creative",
  },
];